spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mbti_collector
    username: root
    password: qijcoj-2naqky-gythUt
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MY_MAIL}
    password: ${MAIL_PW}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  thymeleaf:
    check-template-location: false
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              MySQL5Dialect:
  sql.init.mode: always

  springdoc:
    version: '@project.version@'
    api-docs:
      path: /api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
      operations-sorter: alpha
      tags-sorter: alpha
      path: /swagger-ui.html
      disable-swagger-default-url: true
      display-query-params-without-oauth2: true
      doc-expansion: none
    paths-to-match:
      - /api/**

# JWT Configuration
jwt:
  secret: YOUR_JWT_SECRET_KEY
  token-expiration: 3600000  # 1 hour in milliseconds

# 세션 타임아웃 설정 (예: 30분)
  server.servlet.session.timeout: 30m

server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: acrofuture
    key-alias: tomcat
  port : 8443